<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ProjectLoanManagement.Interfaces\ProjectLoanManagement.Interfaces.csproj" />
    <ProjectReference Include="..\ProjectLoanManagement.Models\ProjectLoanManagement.Models.csproj" />
  </ItemGroup>
</Project>
